### ISSUE TITLE
lit review

### ISSUE THREAD

**Issue by timm** [ai-se/amesModels#4]
- [ ] 188 citations, 2002: Alex Groce and Willem Visser. 2002. [Heuristic Model Checking for Java Programs](http://www.researchgate.net/profile/Alex_Groce/publication/2561037_Model_Checking_Java_Programs_using_Structural_Heuristics/links/00b7d51436151c9e14000000.pdf). In Proceedings of the 9th International SPIN Workshop on Model Checking of Software, Dragan Bosnacki and Stefan Leue (Eds.). Springer-Verlag, London, UK, UK, 242-245. http://dl.acm.org/citation.cfm?id=672223
- [ ] 35 citations, 2011: Domagoj Babić, Lorenzo Martignoni, Stephen McCamant, and Dawn Song. 2011. [Statically-directed dynamic automated test generation](http://bitblaze.cs.berkeley.edu/papers/testgen-issta11.pdf). In Proceedings of the 2011 International Symposium on Software Testing and Analysis (ISSTA '11). ACM, New York, NY, USA, 12-22. DOI=10.1145/2001420.2001423 http://doi.acm.org/10.1145/2001420.2001423

**Comment by neharungta** [comment]
The paper by Alex and Willem is super old. For the types of things we want to do -- those heuristics won't do us any good.There is a lot more newer work -- including by yours truly! My Phd work was related to development of heuristics for bug detection.

**Comment by timm** [comment]
oh, do tell... what should i be reading from https://goo.gl/zuoqwD ?

**Comment by neharungta** [comment]
I am not sure at the moment whether any of the heuristics in the domain of software model checking / verification will be relevant directly to the problem we want to tackle. Let me read and digest the GALE paper (its on my to do task list for today) and then weigh in on the related work.

**Comment by timm** [comment]
you are right. i have a dream of, in the future, using GALE as a feature extractor that can be used to usefully reign in the state space explosion problem. 

for now, the questions are:
- [ ] can we find a path from HERO to something we care about
  - I say yes, see #2 
- [ ] what kinds of budgets do we need to play together
  - Need this to see if we can work
- [ ] what is needed for this proposal for sept4? a full document? or a letter of intent?
