### ISSUE TITLE
Internship for Spring 2016

### ISSUE THREAD

**Issue by neharungta** [ai-se/amesModels#5]
https://intern.nasa.gov/ossi/web/public/main/index.cfm?solarAction=view&subAction=studentCal

I have posted an opportunity for Spring 2016 in the NASA OSSI system. If you can identify a student who would be a good fit (and is a US citizen), that would be fantabolous! 

The title of the opportunity is "Modeling and Analysis for Human System Integration in the National Airspace (NAS)"

The dates for application are 

06/02/2015 - 11/09/2015
    Submit Internship Application for Spring 2016 Session

**Comment by timm** [comment]
noted. lets touch base on this come early october and i'll offer you and endorsement of one such person
